name: trouvetout
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  woocommerce_api: ^0.1.0
  flutter_wp_woocommerce: ^1.0.0
  get_storage: ^2.0.3
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.1
  retry: ^3.1.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  badges: ^3.0.1
  flutter_widget_from_html: ^0.9.1
  logger: ^1.1.0
  flutter_cart: ^0.0.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/image/
  fonts:
    - family: Metro
      fonts:
        - asset: assets/font/metropolis.bold.ttf
          weight: 400
        - asset: assets/font/metropolis.medium.ttf
          weight: 500
        - asset: assets/font/metropolis.regular.ttf
          weight: 600
        - asset: assets/font/metropolis.semi-bold.ttf
          weight: 700

